server:
  port: 8080
  servlet:
    context-path: /users

management:
  endpoints:
    web:
      exposure:
        include: health,info
        #include: health,info,metrics
      base-path: /actuator
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  health:
    db:
      enabled: true

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_ACCESS_EXPIRATION:900000}           # access token : 15 min
  refresh-expiration: ${JWT_REFRESH_EXPIRATION:604800000} # refresh token : 7 jours

spring:
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
  logging:
    level:
      org.springframework.security: DEBUG
      org.springframework.web: DEBUG
  application:
    name: authentification-service
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
      jdbc:
        batch_size: 20
    show-sql: false
  flyway:
    enabled: true
    baseline-on-migrate: true
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    from: ${MAIL_FROM:${MAIL_USERNAME}}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  security:
    enabled: true
    web:
      ignored:
        - /users/actuator/**