# Utiliser une base H2 en mémoire pour les tests
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA pour les tests
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop

# Désactiver les services externes
spring.mail.host=localhost
spring.mail.port=9999

# Logs pour debug
logging.level.org.springframework.boot.test=DEBUG