apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: authentification-service
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/OWNER/REPO.git
    targetRevision: main
    path: deploy/helm/authentification-service
    helm:
      releaseName: authentification-service
  destination:
    server: https://kubernetes.default.svc
    namespace: authentification
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
